apiVersion: v1
kind: Pod
metadata:
  name: s3client
spec:
  containers:
  - name: s3client
    image: dxd360/s3cli:0.0.1
    imagePullPolicy: Always
    volumeMounts:
    - name: cosi-secrets
      mountPath: /data/cosi
    env:
      - name: CREDENTIALS_FILE_PATH
        value: "/data/cosi/credentials"
  volumes:
  - name: cosi-secrets
    csi:
      driver: objectstorage.k8s.io
      volumeAttributes:
        bar-name: sample-bar
